const commonEnv = {
  NODE_ENV: "production",

  DATABASE_URL: process.env.DATABASE_URL,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  CONFIG_ENCRYPTION_KEY: process.env.CONFIG_ENCRYPTION_KEY,
  GENERATED_DIR: process.env.GENERATED_DIR,

  // Provider credentials stay server-side. Capability/model selection lives in
  // SystemConfig and can change without exposing these secrets to the browser.
  ZAI_BASE_URL: process.env.ZAI_BASE_URL,
  ZAI_API_KEY: process.env.ZAI_API_KEY,
  ZAI_CHAT_MODEL: process.env.ZAI_CHAT_MODEL || "glm-4-plus",
  XAI_API_KEY: process.env.XAI_API_KEY,
  ELEVENLABS_API_KEY: process.env.ELEVENLABS_API_KEY,
  AI_COMPATIBLE_API_KEY: process.env.AI_COMPATIBLE_API_KEY,

  PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: process.env.PAYSTACK_PUBLIC_KEY,
  HUBTEL_CLIENT_ID: process.env.HUBTEL_CLIENT_ID,
  HUBTEL_CLIENT_SECRET: process.env.HUBTEL_CLIENT_SECRET,
  HUBTEL_MERCHANT_ACCOUNT_NUMBER: process.env.HUBTEL_MERCHANT_ACCOUNT_NUMBER,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  SMTP_FROM: process.env.SMTP_FROM,

  IMAGE_API_KEY: process.env.IMAGE_API_KEY,
  VIDEO_API_KEY: process.env.VIDEO_API_KEY,
  TTS_API_KEY: process.env.TTS_API_KEY,
};

module.exports = {
  apps: [
    {
      name: "vidora",
      script: ".next/standalone/server.js",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      env: {
        ...commonEnv,
        PORT: 3004,
        HOSTNAME: "0.0.0.0",
      },
      max_memory_restart: "1G",
      autorestart: true,
      restart_delay: 3000,
      min_uptime: "10s",
      max_restarts: 10,
      kill_timeout: 15000,
      listen_timeout: 15000,
      watch: false,
      out_file: "./logs/pm2-out.log",
      error_file: "./logs/pm2-error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "vidora-generation-worker",
      script: "scripts/generation-worker.ts",
      interpreter: "bun",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      env: {
        ...commonEnv,
        GENERATION_WORKER_IDLE_MS: process.env.GENERATION_WORKER_IDLE_MS || "3000",
        GENERATION_SUBMISSION_SPACING_MS: process.env.GENERATION_SUBMISSION_SPACING_MS || "15000",
      },
      max_memory_restart: "768M",
      autorestart: true,
      restart_delay: 3000,
      min_uptime: "10s",
      max_restarts: 20,
      kill_timeout: 30000,
      watch: false,
      out_file: "./logs/generation-worker-out.log",
      error_file: "./logs/generation-worker-error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "vidora-export-worker",
      script: "scripts/export-worker.ts",
      interpreter: "bun",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      env: {
        ...commonEnv,
        EXPORT_WORKER_IDLE_MS: process.env.EXPORT_WORKER_IDLE_MS || "3000",
        EXPORT_WORKER_STALE_MINUTES: process.env.EXPORT_WORKER_STALE_MINUTES || "3",
      },
      max_memory_restart: "1G",
      autorestart: true,
      restart_delay: 3000,
      min_uptime: "10s",
      max_restarts: 20,
      kill_timeout: 60000,
      watch: false,
      out_file: "./logs/export-worker-out.log",
      error_file: "./logs/export-worker-error.log",
      merge_logs: true,
      time: true,
    },
  ],
};
